### ISSUE TITLE
direction star rtl

### ISSUE THREAD

**Issue by davodaslanifakor** [craigh411/vue-star-rating#11]
this is my rate
![rating](https://cloud.githubusercontent.com/assets/14367811/26057954/ede3a79c-3990-11e7-9e50-7a915ef6e73f.png)

this is my cod 
`<star-rating  :rating="3.37" :increment="0.01"	:read-only="true" :star-size="20"></star-rating>`
how solve,
thank for help...

**Comment by craigh411** [comment]
I didn't consider `rtl`, however, it shouldn't be too difficult to fix this, so I'll try to get a new release out with `rtl` support this week.

**Comment by davodaslanifakor** [comment]
@craigh411 
Thank you I waiting...
Tell me when was solved thanks

**Comment by craigh411** [comment]
`rtl` support has now been added in [version 1.4.0 ](https://github.com/craigh411/vue-star-rating/releases/tag/v1.4.0) so you can simply pass the `rtl` prop like so:

`<star-rating :rtl="true" :rating="3.37" :increment="0.01" :read-only="true" :star-size="20"></star-rating>`

I've also added this to the [JSFiddle examples](https://jsfiddle.net/craig_h_411/992o7cq5/)
