### ISSUE TITLE
Unable to resize

### ISSUE THREAD

**Issue by alvirtuoso** [craigh411/vue-star-rating#12]
![screen shot 2017-05-16 at 2 39 06 pm](https://cloud.githubusercontent.com/assets/3849845/26129666/047b907c-3a46-11e7-9b21-b1168b71f111.png)

Here's my markup:
` <star-rating :rating="3.8"  :star-size="30" :read-only="true" :increment="0.01"></star-rating>`

**Comment by smccumsey** [comment]
Seeing same issue. Works when I wrap it in spans (idk why) though.

```          
<span><star-rating :star-size="30" :show-rating="false" :rating="4" :inline="true" :active-color="`darkgrey`" ></star-rating></span>
```

**Comment by craigh411** [comment]
I can't seem to reproduce this. What browser is this appearing in? Also, do you have any styles that might be overriding the `.star-rating`, `.star` classes, something like [this JSFiddle](https://jsfiddle.net/z66baswk/) gets close to what you are seeing. If this is the case I will consider changing the class names inside the component so it's not so easy to override them.

**Comment by smccumsey** [comment]
I have Google Chrome Version 58.0.3029.110 (64-bit)

And for the js fiddle I'm not sure if this is what you meant but when I added the class "container__stars" to star-rating component then changed '.star-rating' to '.container__stars' in the CSS the stars were still cut off.

**Comment by craigh411** [comment]
Do you still see cut off stars in [this fiddle](https://jsfiddle.net/dw1q67L6/) without any css?

**Comment by smccumsey** [comment]
w/o the css the stars aren't cut off

**Comment by craigh411** [comment]
Ah, OK, then this may just be a case of making the overflow visible on the stars. Thanks for your responses, they are really appreciated.

**Comment by alvirtuoso** [comment]
@craigh411  Tested with empty .star-rating css and all is fine. Thanks for this component, btw!

**Comment by craigh411** [comment]
OK, I've now changed the internal class names so it shouldn't be so easy to unintentionally override the default styles. See the release notes for [version 1.4.0](https://github.com/craigh411/vue-star-rating/releases/tag/v1.4.0)
