### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by murwa** [craigh411/vue-star-rating#15]
Could we have validation for when used in a form?

**Comment by craigh411** [comment]
Validation would usually be done on the data being returned from the component. Are you looking for some kind of visual queue, such as a red border to show that the user needs to add input?

**Comment by murwa** [comment]
Yeah kinda off. Coz at the moment, I have simple use case, where I think just disabling the submit button will do; but it could come in handy in other scenarios, my thoughts!

And by the way, thanks for this.

**Comment by craigh411** [comment]
I've taken a look at this and it can already be done easily in user land:

```JavaScript
new Vue({
  el: '#app',
  methods: {
    validate() {
      if (this.rating === 0) {
        this.borderColor = 'pink';
        this.msg = 'Please enter a rating'
      } else {
        this.msg = 'All OK!'
      }
    },
  },
  watch: {
    rating(value) {
      if (value > 0) {
        this.borderColor = '#000';
      }
    }
  },
  data: {
    rating: 0,
    borderColor: '#000',
    msg: ''
  }
});
```

See:  https://jsfiddle.net/eb1gsz0q/
