### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by Neve12ende12** [craigh411/vue-star-rating#20]
I keep getting the error described in the title when trying to load the component.

```
// HTML
<div class="container" id="main">        
    <star-rating></star-rating>
</div>

// Javascript
var StarRating = require('vue-star-rating');
var Vue = require('vue');
Vue.component('star-rating', StarRating);

new Vue({
    el: "#main",
    data: {
         
    },
    methods: {
        
    },
    mounted: function() {
        window.Laravel.debug && console.log('Survey Vue Mounted!');
    }
});
```

**Comment by murwa** [comment]
Have you tried:-
` import StarRating from 'vue-star-rating';`

**Comment by craigh411** [comment]
You are importing the runtime-only build of vue, which does not include the compiler (see: [Runtime + Compiler vs. Runtime-only](https://api.mailgun.net/v3/mg.cleverclogs.io)). You either need to import the runtime + compiler build as outlined in the docs, use the CDN or define a render function for a base component that serves up your views. This ultimately means you end up with one view model (usually in a file called app.js) that looks like this:

```
import App from 'App.vue'; // Base component that serves all view

new Vue({
  render: h => h(App)
}).$mount('#app');
```

You would then use `vue-router` in you base up to serve those views, which you webpack up into a single JavaScript file and include in your index.html page.

**Comment by Neve12ende12** [comment]
import StarRating from 'vue-star-rating'; fixed the problem.  Thank you.
