### ISSUE TITLE
Selenium testing can not pick up star rating

### ISSUE THREAD

**Issue by ihaseeb** [craigh411/vue-star-rating#25]
I was trying to record a test case on selenium testing and when i try to record star rating selenium does not pick the click

**Comment by craigh411** [comment]
Hello, I've never used Selenium so I'm not sure how to help you with this. You may be able to get more help from [StackOverflow](https://stackoverflow.com/questions/tagged/selenium). I'm going to close for now, but if you do find there is a problem my end let me know and I'll re-open the issue.
