### ISSUE TITLE
Add custom parameter to showCurrentRating function

### ISSUE THREAD

**Issue by rnjailamba** [craigh411/vue-star-rating#27]
For example i need showCurrentRating(rating, meeting)
where meeting is another object
Reference -https://jsfiddle.net/jdzbyzke/

**Comment by craigh411** [comment]
if you need to pass addition parameters, you can simply pass `$event` as the first parameter, like so:

```
showCurrentRating($event, meeting)
```

See [this JSFiddle](https://jsfiddle.net/s81s8x08/)

**Comment by rnjailamba** [comment]
Perfect!!
