### ISSUE TITLE
Remove rating?

### ISSUE THREAD

**Issue by luminous8** [craigh411/vue-star-rating#29]
Nice plugin but Is there a way to remove the rating?
Example : I rate 5 but finally I want to delete my rating, I should be able to do it by clicking on the left of the 1st star

**Comment by craigh411** [comment]
The main issue with removing the rating by clicking part of the star is that `increments` are customizable, so this wouldn't work across the board (for example what part of the star would reset it when increments are 0.01?). It is however, pretty straightforward to create your own reset button:

**Markup**
```html
<div id="app">
  <star-rating v-model="rating"></star-rating>
  <br />
  <a href="#" @click.prevent="rating = 0">Reset</a>
</div>
 ```

**Vue Instance**

```JavaScript
Vue.component('star-rating', VueStarRating.default)

new Vue({
  el: "#app",
  data() {
    return{
      rating: 2
   }
  }
})
```

Here's the [JSFiddle](https://jsfiddle.net/zh8t26tf/)

Let me know if you have any other ideas for resetting the stars, I will be happy to consider them.

**Comment by luminous8** [comment]
It will do the trick! thanks @craigh411

**Comment by NeoMarine** [comment]
I simply add some whitespace to the left of the <star-rating> component like so:
`<div class="float-left cursor-pointer" style="width:10px; height:40px;" v-on:click.prevent="rating=0"></div><star-rating value="rating" v-model="rating" :star-size="40" :increment="0.5"></star-rating>`

This looks nicer than having a "reset" button.
