### ISSUE TITLE
current-rating event isn't fired on mouse leave

### ISSUE THREAD

**Issue by davidsielert** [craigh411/vue-star-rating#32]
event is not fired when mouse leaves component, however I see from dev-tools that the current rating is reset to 0 ..

**Comment by SparoHawk** [comment]
I just tested this in [JSFiddle](https://jsfiddle.net/fhj35zq0/) and it works correctly. Could you present an example of the code you are having issues with?

**Comment by craigh411** [comment]
As there's been no response to this and we are unable to replicate it, I'll assume that the problem lies elsewhere, so I'll close this for now. Please let me know if this issue re-occurs and I'll look in to it.

**Comment by marcellofuschi** [comment]
Experiencing the same problem here: there is no event fired when the mouse cursor leaves the component that tells you what the currently selected rating is.
