### ISSUE TITLE
config global how it work?

### ISSUE THREAD

**Issue by davodaslanifakor** [craigh411/vue-star-rating#35]
hi boy 
i want add global config so add this 
```import StarRating from 'vue-star-rating'
Vue.component('star-rating', StarRating);
Vue.use('star-rating',StarRating, {
  'rounded-corners':true,
  'borderColor':'red'
});
```
or 
```
import StarRating from 'vue-star-rating'
Vue.component('star-rating', StarRating, {
    'rounded-corners':true,
    'borderColor':'red'
  });
```

but don't work how add config global?
Tnx for help ...

**Comment by craigh411** [comment]
I haven't set this up to allow a global config like that, it's usually better to declare these on the component itself. It may, however, be possible to extend the component by wrapping it in a `Vue.extend()` and then overridding the default props values.
