### ISSUE TITLE
round-start-rating is respected after first hover

### ISSUE THREAD

**Issue by sventendo** [craigh411/vue-star-rating#36]
This is how I set the initial rating.

```
    <star-rating ref="widget"
        v-model="rating"
        @rating-selected="setRating"
        :round-start-rating="false">
     </star-rating>

```

```
        beforeMount: function() {
            this.ratingIdentifier = this.getRatingIdentifier();
            this.readOnly = undefined !== localStorage[this.ratingIdentifier];
            this.maxRating = window.vueData.rating.maxRating;
            this.getRating();
        },
        methods: {
            getRating: function() {
                  // 3.5 is actually from an async callback
                  this.rating = 3.5;
            }
        }
```

Expected behavior:
- initial rating shows 3 1/2 stars.
- rating should be possible in increments of 1, no half stars

Actual behavior:
- initial rating shows as 4 stars.
- rating is possible in increments of 1, no half stars
- after hovering (not selecting anything) the widget shows a rating of 3 1/2 stars.

Am I setting the rating at a wrong time?

I'm using version 1.6

**Comment by craigh411** [comment]
Thanks for opening the issue, this shouldn't happen, but it appears to be an issue with the async call. I've set up a JSFiddle to show the issue: https://jsfiddle.net/fhj35zq0/22/ and I'll look in to getting this fixed ASAP,
