### ISSUE TITLE
Star inactive opacity

### ISSUE THREAD

**Issue by AlbertCloete** [craigh411/vue-star-rating#38]
I want to be able to make my stars transparent. 

I can do this in Chrome by setting the `inactive-color` to a color that has opacity, e.g. #000000, or rgba(0, 0, 0, 0).

This unfortunately doesn't work in Safari, because SVG grandients ignore color opacity in the `stop` elements inside the linear-gradient element. To get it to work you need to set an attribute `stop-opacity` on the `stop` element inside the gradient. To see what I mean, you can open this CodePen in Chrome and Safari and see the difference: https://codepen.io/AmeliaBR/pen/jrBOBv/

So I'd like to add an attribute on this star rating component called `inactive-opacity` or something like that, which would then set the opacity for the inactive gradient stops.

If you'd agree that it would be a useful feature for the component, I'll see if I can add it and make a pull request.

**Comment by craigh411** [comment]
@greenhatman Feel free to submit a PR and I'll happily take a look at it. :)
