### ISSUE TITLE
Stars look pixelated with high contrast

### ISSUE THREAD

**Issue by marconett** [craigh411/vue-star-rating#39]
This can be seen on the JSFiddle example linked in the readme for the red stars on non-retina displays:
![sc](https://user-images.githubusercontent.com/3315507/44785368-f04cb780-ab90-11e8-9cea-fffafbf2f7ae.png).

It looks fine on a retina display though.

Tested and reproducible on macOS with most recent chrome, firefox and safari.

I suppose it's a problem with the svgs, but I'm not very familiar with the format or svg rendering.

**Comment by craigh411** [comment]
That's interesting. I don't have  a machine to test this on at the moment, so it's going to be difficult for me to know if any fixes work, but if you or somebody else knows how to resolve the issue feel free to put in a PR.
