### ISSUE TITLE
Set the repo of this GitHub URL

### ISSUE THREAD

**Issue by dandv** [craigh411/vue-star-rating#4]
Presumably to https://jsfiddle.net/craig_h_411/992o7cq5/

**Comment by craigh411** [comment]
Thanks for raising the issue. I'm not sure I understand what you mean, where do you want me to set that?

**Comment by dandv** [comment]
[![image](https://cloud.githubusercontent.com/assets/33569/4949884/c2b69bde-6651-11e4-88eb-8fdf8e8c9f0a.png)](https://github.com/dandv/meteor-jquery-rateit)

**Comment by craigh411** [comment]
No problem. Thanks.
