### ISSUE TITLE
Screen Reader support

### ISSUE THREAD

**Issue by dustinleblanc** [craigh411/vue-star-rating#40]
Thanks for a very useful component! I am making use of this project to provide star ratings on a project and we're aiming for a great experience for screen reader users. Currently, when a screen reader hits the star ratings it just skips it.

My quick solution on my app was to do this:

```vue
<div class="ratings">
    <span class="sr-only">This clinic is rated {{ rating }} stars out of five.</span>
    <star-rating v-model="rating"
                       :show-rating="false"
                       active-color="#d6612d"
                       :star-size="20"
      ></star-rating>
</div>
```

By adding that span, the screen reader gets a solid sensible experience, perhaps it would be a good idea to have something like it by default that is visually hidden but translates the component contents to something that verbally makes sense?

**Comment by craigh411** [comment]
Thanks for this, I'll see if I can get this in in the the next release. :)
