### ISSUE TITLE
iOS devices require "double tap" to select rating

### ISSUE THREAD

**Issue by gmcz** [craigh411/vue-star-rating#46]
I seem to be having an issue where the rating only works on iOS if you double-tap the star. I suspect this has to do with using mouseevents, but I'm not sure.

The stars appear to be selected (they turn yellow) but the v-model is only updated with a second tap on the same star.

**Comment by gmcz** [comment]
Well, for anyone else dealing with this and also inexperienced building and modifying vue components: I ended up just using my own solution based on this CSS-only example of star rating: https://codepen.io/jexordexan/pen/yyYEJa

**Comment by xEsk** [comment]
An option to disable the mouse hover functionality on touch devices would be fantastic.

I tried to "fix" it by myself, but I'm too new to Vue's world, hehe.

**Comment by craigh411** [comment]
I've added better touch support for the forthcoming minors versions, so hopefully this will no longer be an issue.
