### ISSUE TITLE
Can i change the svg of Stars?

### ISSUE THREAD

**Issue by husnainProgz** [craigh411/vue-star-rating#53]
Hi, is there a way to change the default svg of star to my own svg?

**Comment by craigh411** [comment]
Hello,

Sorry, I forgot to put this isn't in the documentation. There is a [star-points](https://github.com/craigh411/vue-star-rating/blob/cdd732ce4affa0ef5d28b350a37b09122f15d111/src/star-rating.vue#L46) prop which accepts an array of SVG points:

e.g. 

```
<star-rating  :rounded-corners="true" :star-points="[23,2, 14,17, 0,19, 10,34, 7,50, 23,43, 38,50, 36,34, 46,19, 31,17]"></star-rating>
```
