### ISSUE TITLE
How to make some  star-rating elements disabled 

### ISSUE THREAD

**Issue by sergeynilov** [craigh411/vue-star-rating#57]
Hello,
In vuejs 2.6 app I use
"vue-star-rating": "^1.6.1"
and having listing of star-rating elements I need to make some of them disabled for clicking.
I found some hints on the site, like

```
                    <star-rating
                        v-model="nextHostelReview.stars_rating_type_id"
                        isIndicatorActive="true"
                        :config="config"
                        :max-rating="nextHostelReview.stars_rating_type_id"
                        :min-rating="nextHostelReview.stars_rating_type_id"
                        :rating="nextHostelReview.stars_rating_type_id"
                        :star-size="20"
                    ></star-rating>

```
but I failed.
I need something like :
```
                    <star-rating
                    ...
                        disabled="true"
                        readonly="true"
                    ></star-rating>


```Are there ?

Thanks!

**Comment by webdesignberlin** [comment]
Hi @sergeynilov ,

seems u look for the read-only prop? https://github.com/craigh411/vue-star-rating/blob/cdd732ce4affa0ef5d28b350a37b09122f15d111/src/star-rating.vue#L60

From Readme: read-only | When set to true, the rating cannot be edited. Use in conjuction with increment to define rounding precision. Default: false

Hope it helps. Best Regards
