### ISSUE TITLE
hover event for vue-star-rating

### ISSUE THREAD

**Issue by Jasmin2895** [craigh411/vue-star-rating#62]
Hey,

I am using vue-star-rating in one of my projects and came across a scenario where I want to do something on the hover action. Currently, there is no event for that specifically.  Can we have a hover event along with the other two?

**Comment by craigh411** [comment]
Hey Jasmin,

Sorry it's taken so long to get back to you. What do you mean by a hover event? The component emits an event on mouse move (current-rating) and on click (rating-selected). Do you mean hover over the entire component? if that's the case you can just wrap it in a div:

```javascript
<div @mouseover="myFunc">
  <star-rating />
</div>
```

**Comment by Jasmin2895** [comment]
Hey @craigh411 ,

My concerns were related to the entire component hover. I implemented the same way as you explained above and added some setTimeout() to it so that it didn't capture every mouseover.

Thank you so much for your reply.
