### ISSUE TITLE
Fix Expected Number with value, got String error

### ISSUE THREAD

**Issue by madsongr** [craigh411/vue-star-rating#63]
Hi, I'm starting with vue.js and I implemented star-rating. Everything is working fine: I can get the rating value from database and update it by clicking on the stars.

But I get this message when page loads and on click event:

`[Vue warn]: Invalid prop: type check failed for prop "rating". Expected Number with value 2, got String with value "2".`

my code:
```
<div v-for="(item, index) in hosters" v-bind:key="item.id" class="col-md-6 mb-50">
    <div class="result-rating">
        <star-rating @rating-selected="setRating(item.id, item.rating)" v-model='item.rating'></star-rating>
    </div>
</div>
```

```
let app = new Vue({
    el: '#app',
    data: {
        city: 'mycity',
        hosters: null,
        selectedImage: null,
        openModal: false,
        showTour: false,
        tourSelect: '',
        rating: 0
    },
    created: function () {
        this.searchHoster()
    },
    methods: {
        searchHoster: function () {
            axios.post('searchHoster.php', { "city": this.city }).then((response) => {

                this.hosters = response.data.hosters;
                console.log(this.hosters);

            }).catch((error) => {
                console.log(error);
            });
        },
        setRating: function (id, rating) {
            axios.post('updateRating.php', { "id": id, "rating": rating }).then(res => {
                console.log(res);
            });
        }
    }
});
```

I've tried to declare rating as a prop but it didn't work. May I get your help? Thank you!

**Comment by craigh411** [comment]
Sorry I didn't get back to you on this. I'm sure you've solved this by now, but please feel free to re-open if you're still having trouble.

**Comment by madsongr** [comment]
Yep. I'm returning a number from database instead of a string. Thanks.

**Comment by craigh411** [comment]
My best guess is that your rating is actually being represented as a string, something like:

```javascript
      this.hosters = [{
        id: 1,
        rating: "5"
      }, {
        id: 2,
        rating: "3"
      }]
    }
```

so you're going to need to use parseInt(). The easiest way would be to use a computed to map the array:

```javascript
    hostersSanitized() {
      return this.hosters.map(item => 
        Object.assign(item, {
          rating: parseInt(item.rating)
        })
      )
    }
```

Now you can use v-for on the computed instead:

```html
  <div v-for="(item, index) in hostersSanitized" v-bind:key="item.id">
      <star-rating v-model="item.rating" />
  </div>
```

Here's the JSfiddle: https://jsfiddle.net/craig_h_411/nvtcjyqh/
