### ISSUE TITLE
The prop round-start-rating is incorrectly named

### ISSUE THREAD

**Issue by tylermurry** [craigh411/vue-star-rating#67]
Unless I'm misunderstanding something, the `round-start-rating` prop is misspelled and should be `round-star-rating`.

**Comment by craigh411** [comment]
`round-start-rating` is correct. When you set the `increment` prop, the initial rating passed to the component is automatically rounded to that increment (so 4.25 would become 4.5 with increment set to 0.5). Some users wanted to display a precise rating when the component loaded, but allow users to vote in a particular increment which is what `round-start-rating` allows you to do.

If you're interested, you can find the discussion on issue https://github.com/craigh411/vue-star-rating/issues/21
