### ISSUE TITLE
Warning: Attribute :read-only is not serializable as XML 1.0.

### ISSUE THREAD

**Issue by bsam2019** [craigh411/vue-star-rating#69]
Everything seems to work fine, however, I get the error below when I try to validate my HTML

Warning: Attribute :read-only is not serializable as XML 1.0.

**Comment by craigh411** [comment]
I have seen some discussion about this in the past, but it's more to do with the way Vue works and not an issue with the component itself. See: https://stackoverflow.com/questions/39498365/w3c-validation-and-vues-html-binding-syntax and https://stackoverflow.com/questions/41510440/vue-js-app-not-passing-html-validation
