### ISSUE TITLE
[suggestion] v-model implementation?

### ISSUE THREAD

**Issue by acro5piano** [craigh411/vue-star-rating#9]
Thanks for your great library!
I am really happy to use it.

This is not a problem but just a suggestion.
For reactive data binding, I wrote the following code:

```html
<template>
  <star-rating  
      :rating="rating"
      @rating-selected="value => {rating = value}">
  </star-rating>
</template>

<script>
  new Vue({
    data() {
      return { rating: 3 }
    }
  })
</script>
```

How about to set reactive `v-model` attribution?
The code should be like this, simply:

```html
<template>
  <star-rating v-model="rating"></star-rating>
</template>
```

I think we can do it by adding `value` prop to `star-rating` component and emit `input` event with the argument `this.selectedRating`.

If you accept this feature, I will try to code. 

Thanks!

**Comment by craigh411** [comment]
Absolutely, I think that's a much cleaner solution. Feel free to submit a PR, but if you don't have the time I'll definitely add this.

**Comment by acro5piano** [comment]
Thanks for your quick response!
I will write some code during this weekend.
